require("dukcode.core.options")
require("dukcode.core.keymaps")
require("dukcode.core.colorscheme")
require("dukcode.plugins-setup")
require("dukcode.plugins.comment")
require("dukcode.plugins.nvim-tree")
require("dukcode.plugins.lualine")
require("dukcode.plugins.telescope")
require("dukcode.plugins.nvim-cmp")
require("dukcode.plugins.autopairs")
require("dukcode.plugins.treesitter")

